<a href="https://colab.research.google.com/github/hahustat/PyTorch-tutorial-Nov8-24/blob/main/October3_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#changes

In [ ]:
a=['tedros','Geb']
for i in a:
  print(i)
  print(''.join(i))

# joining lis
''.join(a)

tedros
tedros
Geb
Geb


'tedrosGeb'

Download shakespare dataset from https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

In [ ]:
pwd # Where I am in colab directory

'/content'

In [ ]:
import os
import pickle
import requests
import numpy as np

# download the tiny shakespeare dataset
input_file_path = os.path.join(os.path.dirname('/content'), 'input.txt')
if not os.path.exists(input_file_path):
    data_url = 'https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt'
    with open(input_file_path, 'w') as f:
        f.write(requests.get(data_url).text)
#
with open(input_file_path, 'r') as f:
    data = f.read()
print(f"length of dataset in characters: {len(data):,}")

length of dataset in characters: 1,115,394


In [ ]:
# get all the unique characters that occur in this text
chars = sorted(list(set(data)))
vocab_size = len(chars)
print("all the unique characters:", ''.join(chars))
print(f"vocab size: {vocab_size:,}")

# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
def encode(s):
    return [stoi[c] for c in s] # encoder: take a string, output a list of integers
def decode(l):
    return ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# create the train and test splits
n = len(data)
train_data = data[:int(n*0.9)]
val_data = data[int(n*0.9):]

all the unique characters: 
 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
vocab size: 65


In [ ]:
# encode both to integers
train_ids = encode(train_data)
val_ids = encode(val_data)
print(f"train has {len(train_ids):,} tokens")
print(f"val has {len(val_ids):,} tokens")

train has 1,003,854 tokens
val has 111,540 tokens


In [ ]:
print(train_data[:100])
print(train_ids[:10])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You
[18 47 56 57 58  1 15 47 58 47]


In [ ]:
import torch
train_ids_ten=torch.tensor(train_ids, dtype=torch.long)

In [ ]:
torch.randint(10,(3,))

tensor([6, 1, 2])

In [ ]:
# export to bin files
train_ids = np.array(train_ids, dtype=np.uint16)
val_ids = np.array(val_ids, dtype=np.uint16)
train_ids.tofile(os.path.join(os.path.dirname('/content'), 'train.bin'))
val_ids.tofile(os.path.join(os.path.dirname('/content'), 'val.bin'))

In [ ]:
meta = {
    'vocab_size': vocab_size,
    'itos': itos,
    'stoi': stoi,
}
with open(os.path.join(os.path.dirname('/content'), 'meta.pkl'), 'wb') as f:
    pickle.dump(meta, f)


In [ ]:
tt=encode(train_ids)

KeyError: 18

In [ ]:
a=['tedros','Geb']
out=[]
for i in a:
  out.append(i)
  print(out)
  print(''.join(out))

['tedros']
tedros
['tedros', 'Geb']
tedrosGeb


In [ ]:
x=torch.arange(12, dtype=torch.float32)
x.numel()

12

In [ ]:
x.shape

torch.Size([12])

In [ ]:
x=torch.arange(12).reshape(3,4)
y=torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
before=id(x)
print(id(x))

133063569739744


In [ ]:
x+=y
print(id(x))
#
before == id(x)

133063569739744


True

In [ ]:
import numpy as np
np.sum(x)

TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:
 * (*, torch.dtype dtype)
      didn't match because some of the keywords were incorrect: out, axis
 * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)
 * (tuple of names dim, bool keepdim, *, torch.dtype dtype)


In [ ]:
a=torch.numpy(x)
#np.sum(a)

AttributeError: module 'torch' has no attribute 'numpy'

In [ ]:
a=x.numpy()

In [ ]:
np.sum(a)

96

In [ ]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [ ]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [ ]:
cd ..

/


# New Section

In [ ]:
A=torch.arange(6).reshape(2,3)
A

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
A_m=A.sum(axis=1, keepdim=True)
A_m

tensor([[ 3],
        [12]])

In [ ]:
A/A_m

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [ ]:
A

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
A.cumsum(axis=0)

tensor([[0, 1, 2],
        [3, 5, 7]])

In [ ]:
A.cumsum(axis=1)

tensor([[ 0,  1,  3],
        [ 3,  7, 12]])

save

In [10]:
zzass

NameError: name 'zzass' is not defined

In [11]:
ssss

NameError: name 'ssss' is not defined

asdd